# Generated by Django 5.2.6 on 2025-09-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalcompanies',
            old_name='name',
            new_name='Total',
        ),
    ]
