# Generated by Django 5.2.6 on 2025-09-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_rename_name_totalcompanies_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalcompanies',
            old_name='Total',
            new_name='total',
        ),
    ]
