# Generated by Django 5.2.6 on 2025-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_rename_total_totalcompanies_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('designation', models.CharField(blank=True, max_length=64, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='testimonial_profile/')),
                ('testimonial', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
