# Generated by Django 5.2.6 on 2025-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbot_inquiries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='processes',
            field=models.IntegerField(default=0),
        ),
    ]
