# Generated by Django 5.2.6 on 2025-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_chatbot_inquiries_customuser_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
