# Generated by Django 5.2.6 on 2025-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subsciption_plan_name',
            field=models.CharField(default='free', max_length=32),
        ),
    ]
