# Generated by Django 5.2.6 on 2025-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
