# Generated by Django 5.2.6 on 2025-09-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0002_remove_team_department_team_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='department',
        ),
    ]
