# Generated by Django 5.2.6 on 2025-09-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0004_alter_project_department_alter_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
