# Generated by Django 5.2.6 on 2025-09-27 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0005_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdealPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('activity_name', models.CharField(max_length=100)),
                ('average_time_minutes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_app.project')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
