# Generated by Django 5.2.6 on 2025-10-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0006_happypath_idealpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealpath',
            name='project',
        ),
        migrations.DeleteModel(
            name='HappyPath',
        ),
        migrations.DeleteModel(
            name='IdealPath',
        ),
    ]
