# Generated by Django 5.2.6 on 2025-10-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0008_happypath'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kpi_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
