# Generated by Django 5.2.6 on 2025-10-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0009_kpilist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kpiList',
        ),
    ]
