# Generated by Django 5.2.6 on 2025-10-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0011_visualization_kpilist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpilist',
            name='visuslization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining_app.visualization'),
        ),
    ]
