# Generated by Django 5.2.6 on 2025-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0012_alter_kpilist_visuslization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpilist',
            name='visuslization',
        ),
        migrations.AddField(
            model_name='kpilist',
            name='visualizations',
            field=models.ManyToManyField(blank=True, to='mining_app.visualization'),
        ),
    ]
