# Generated by Django 5.2.6 on 2025-10-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0014_kpidashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_projects', to='mining_app.project'),
        ),
    ]
