# Generated by Django 5.2.6 on 2025-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0015_project_related_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
