# Generated by Django 5.2.6 on 2025-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0016_project_is_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidashboard',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpidashboard',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
