# Generated by Django 5.2.6 on 2025-10-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0017_alter_kpidashboard_data_alter_kpidashboard_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variant_path', models.TextField(verbose_name='Process Variant Path')),
                ('case_count', models.IntegerField(verbose_name='Case Count')),
                ('frequency_pct', models.FloatField(verbose_name='Frequency (%)')),
                ('median_cycle_time_hours', models.FloatField(blank=True, null=True, verbose_name='Median Cycle Time (Hours)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_variants', to='mining_app.project', verbose_name='Related Project')),
            ],
            options={
                'ordering': ['-case_count'],
                'unique_together': {('project', 'variant_path')},
            },
        ),
    ]
