# Generated by Django 5.2.6 on 2025-10-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0018_processvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='happypath',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
