# Generated by Django 5.2.6 on 2025-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0019_happypath_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copy',
            field=models.BooleanField(default=False),
        ),
    ]
