# Generated by Django 5.2.6 on 2025-10-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0020_project_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostPerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_name', models.CharField(max_length=128)),
                ('cost_per_h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
