# Generated by Django 5.2.6 on 2025-11-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0021_costperprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='happypath',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
