# Generated by Django 5.2.6 on 2025-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_app', '0022_happypath_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happypath',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
